### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by ShiguangSun** [Xingyu-Lin/softgym#22]
Hi，
I met a new question.   I am using Ubuntu 16.04 LTS, CUDA 9.1.85 and Nvidia driver version 460.73.01.  I am testing on a ubuntu server and entirely outside of docker.
 I got this error,

$ python examples/random_env.py --env_name RopeFlatten --headless 1
Traceback (most recent call last):
  File "examples/random_env.py", line 5, in <module>
    from softgym.registered_env import env_arg_dict, SOFTGYM_ENVS
  File "/home/cxg19/softgym/softgym/registered_env.py", line 1, in <module>
    from softgym.envs.pour_water import PourWaterPosControlEnv
  File "/home/cxg19/softgym/softgym/envs/pour_water.py", line 4, in <module>
    import pyflex
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/cxg19/softgym/PyFlex/bindings/build/pyflex.cpython-36m-x86_64-linux-gnu.so)

Thank you for any help you can offer!

**Comment by Xingyu-Lin** [comment]
Looks like you are using a different gcc/g++ environment between compiling. Compiling and running using the container may solve the problem
