### ISSUE TITLE
Installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by hongtaowu67** [Xingyu-Lin/softgym#38]
Hello,

I am trying to install softgym on 2004. My cuda version is 11.4 and my driver is 470.129. I am using an RTX 3060 card.

I have successfully compiled Pyflex using the command in `prepare_1.0.sh` and `compile_1.0.sh`. However, when I am trying to run the example, I got the following error:
```
Traceback (most recent call last):
  File "examples/random_env.py", line 5, in <module>
    from softgym.registered_env import env_arg_dict, SOFTGYM_ENVS
  File "/home/hongtao/src/softgym/softgym/registered_env.py", line 1, in <module>
    from softgym.envs.pour_water import PourWaterPosControlEnv
  File "/home/hongtao/src/softgym/softgym/envs/pour_water.py", line 4, in <module>
    import pyflex
ImportError: /home/hongtao/src/softgym/PyFlex/bindings/build/pyflex.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
```

I checked that one reason for this problem is that the running cuda version is not matched with the compiled one ([#1705](https://github.com/open-mmlab/mmdetection/issues/1705)). But my compiling cuda version and the one shown from `nvcc -V` are both 11.4.

Is there a solution to this problem? Thanks!

**Comment by yqi19** [comment]
maybe you can try docker?

**Comment by zixuwang-cs** [comment]
> Hello,
> 
> I am trying to install softgym on 2004. My cuda version is 11.4 and my driver is 470.129. I am using an RTX 3060 card.
> 
> I have successfully compiled Pyflex using the command in `prepare_1.0.sh` and `compile_1.0.sh`. However, when I am trying to run the example, I got the following error:
> 
> ```
> Traceback (most recent call last):
>   File "examples/random_env.py", line 5, in <module>
>     from softgym.registered_env import env_arg_dict, SOFTGYM_ENVS
>   File "/home/hongtao/src/softgym/softgym/registered_env.py", line 1, in <module>
>     from softgym.envs.pour_water import PourWaterPosControlEnv
>   File "/home/hongtao/src/softgym/softgym/envs/pour_water.py", line 4, in <module>
>     import pyflex
> ImportError: /home/hongtao/src/softgym/PyFlex/bindings/build/pyflex.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
> ```
> 
> I checked that one reason for this problem is that the running cuda version is not matched with the compiled one ([#1705](https://github.com/open-mmlab/mmdetection/issues/1705)). But my compiling cuda version and the one shown from `nvcc -V` are both 11.4.
> 
> Is there a solution to this problem? Thanks!

I have the same problem as you. How did you solve it?
